// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// quiet: true suppresses dotenv's random promotional "tip" line on every
// load (e.g. ads for unrelated dotenvx/vestauth products) — see the CLI
// output when running any prisma command without it.
config({ quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
